CREATE TABLE IF NOT EXISTS game_data.participant_stats
(
    run_id UUID,
    matchid UInt64,
    participantid UInt8,
    puuid FixedString (78),
    teamid UInt8,
    summonerid String,
    summonerlevel UInt16,
    summonername String,
    riotidgamename String,
    riotidtagline String,
    profileicon UInt16,
    championid Nullable (Int32),
    championtransform UInt8,
    champlevel UInt8,
    champexperience UInt32,
    teamposition Enum8 (
        'UNKNOWN' = 0,
        'TOP' = 1,
        'JUNGLE' = 2,
        'MIDDLE' = 3,
        'BOTTOM' = 4,
        'UTILITY' = 5
    ),
    win UInt8,
    gameendedinearlysurrender UInt8,
    gameendedinsurrender UInt8,
    teamearlysurrendered UInt8,
    kills UInt8,
    deaths UInt8,
    assists UInt8,
    doublekills UInt8,
    triplekills UInt8,
    quadrakills UInt8,
    pentakills UInt8,
    killingsprees UInt8,
    largestkillingspree UInt8,
    largestmultikill UInt8,
    largestcriticalstrike UInt16,
    firstbloodkill UInt8,
    firstbloodassist UInt8,
    firsttowerkill UInt8,
    firsttowerassist UInt8,
    goldearned UInt16,
    goldspent UInt16,
    consumablespurchased UInt8,
    itemspurchased UInt8,
    item0 UInt16,
    item1 UInt16,
    item2 UInt16,
    item3 UInt16,
    item4 UInt16,
    item5 UInt16,
    item6 UInt16,
    totaldamagedealt UInt32,
    totaldamagedealttochampions UInt32,
    physicaldamagedealt UInt32,
    physicaldamagedealttochampions UInt32,
    magicdamagedealt UInt32,
    magicdamagedealttochampions UInt32,
    truedamagedealt UInt32,
    truedamagedealttochampions UInt32,
    damagedealttobuildings UInt32,
    damagedealttoturrets UInt32,
    damagedealttoobjectives UInt32,
    damagedealttoepicmonsters Nullable (UInt32),
    totaldamagetaken UInt32,
    physicaldamagetaken UInt32,
    magicdamagetaken UInt32,
    truedamagetaken UInt32,
    damageselfmitigated UInt32,
    totalheal UInt32,
    totalhealsonteammates UInt32,
    totalunitshealed UInt8,
    totaldamageshieldedonteammates UInt32,
    timeccingothers UInt16,
    totaltimeccdealt UInt16,
    totalminionskilled UInt16,
    neutralminionskilled UInt16,
    totalallyjungleminionskilled UInt16,
    totalenemyjungleminionskilled UInt16,
    baronkills UInt8,
    dragonkills UInt8,
    inhibitorkills UInt8,
    inhibitortakedowns UInt8,
    inhibitorslost UInt8,
    turretkills UInt8,
    turrettakedowns UInt8,
    turretslost UInt8,
    objectivesstolen UInt8,
    objectivesstolenassists UInt8,
    visionscore UInt8,
    wardsplaced UInt8,
    wardskilled UInt8,
    detectorwardsplaced UInt8,
    sightwardsboughtingame UInt8,
    visionwardsboughtingame UInt8,
    visionclearedpings UInt8,
    summoner1id UInt8,
    summoner2id UInt8,
    summoner1casts UInt8,
    summoner2casts UInt8,
    spell1casts UInt16,
    spell2casts UInt16,
    spell3casts UInt16,
    spell4casts UInt16,
    rolebounditem Nullable (UInt16),
    bountylevel Nullable (UInt8),
    timeplayed UInt16,
    totaltimespentdead UInt16,
    longesttimespentliving UInt16,
    allinpings UInt8,
    assistmepings UInt8,
    basicpings UInt8,
    commandpings UInt8,
    dangerpings UInt8,
    enemymissingpings UInt8,
    enemyvisionpings UInt8,
    getbackpings UInt8,
    holdpings UInt8,
    needvisionpings UInt8,
    onmywaypings UInt8,
    pushpings UInt8,
    retreatpings Nullable (UInt8),
    unrealkills UInt8
)
ENGINE = MergeTree
ORDER BY (matchid, participantid, puuid, run_id);
