CREATE TABLE IF NOT EXISTS game_data_filtered.tl_participant_per_minute_stats
(
    matchid String,
    frame_timestamp UInt32,
    participantid UInt8,

    nonchampiondamagedone UInt32,
    nonchampionphysicaldamagedone UInt32,
    nonchampionmagicdamagedone UInt32,
    nonchampiontruedamagedone UInt32,
    spentgold Int32,
    totalfarm UInt32,
    spentgoldratio Float32,
    championdamageshare Float32,
    nonchampiondamageshare Float32,
    physicalchampiondamageshare Float32,
    physicalnonchampiondamageshare Float32,
    magicchampiondamageshare Float32,
    magicnonchampiondamageshare Float32,
    truechampiondamageshare Float32,
    truenonchampiondamageshare Float32,
    championdamagetodamagetakenratio Float32,
    championdamagepergoldearned Float32,
    physicaldamageshare Float32,
    magicdamageshare Float32,
    truedamageshare Float32,
    physicalchampiondamagetypeshare Float32,
    magicchampiondamagetypeshare Float32,
    truechampiondamagetypeshare Float32,
    physicalnonchampiondamagetypeshare Float32,
    magicnonchampiondamagetypeshare Float32,
    truenonchampiondamagetypeshare Float32,
    physicaldamagetakenshare Float32,
    magicdamagetakenshare Float32,
    truedamagetakenshare Float32,
    lanefarmshare Float32,
    junglefarmshare Float32,

    championkilleventsperminutebin UInt16,
    championdeatheventsperminutebin UInt16,
    championassisteventsperminutebin UInt16,
    wardskilledperminutebin UInt16,
    wardsplacedperminutebin UInt16,
    itemsdestroyedperminutebin UInt16,
    itemspurchasedperminutebin UInt16,
    itemundosperminutebin UInt16,
    firstbloodeventsperminutebin UInt16,
    aceeventsperminutebin UInt16,
    multikilleventsperminutebin UInt16,
    doublekilltotalkillsperminutesum UInt16,
    triplekilltotalkillsperminutesum UInt16,
    quadrakilltotalkillsperminutesum UInt16,
    pentakilltotalkillsperminutesum UInt16,
    toplaneplatesdestroyedperminutesum UInt16,
    midlaneplatesdestroyedperminutesum UInt16,
    botlaneplatesdestroyedperminutesum UInt16,
    kdaperminutebin Float32,
    kdperminutebin Float32,
    kaperminutebin Float32,
    killparticipationeventsperminutebin UInt16,
    kdaactivityperminutebin UInt16,
    nettakedownmarginperminutebin Int16,
    visionactivityperminutebin UInt16,
    visiondenialshareperminutebin Float32,
    itemactivityperminutebin UInt16,
    netitempurchaseactionsperminutebin Int16,
    multikillkillshareperminutebin Float32,
    totalplatesdestroyedperminutesum UInt16,
    wardplacementtokillratioperminutebin Float32,
    toplaneplateshareperminutebin Float32,
    midlaneplateshareperminutebin Float32,
    botlaneplateshareperminutebin Float32,
    platelaneconcentrationperminutebin Float32,

    championdamageperdeathevent Float32
)
ENGINE = MergeTree
ORDER BY (matchid, frame_timestamp, participantid);
