-- noqa: disable=LT05
-- Participant-minute GNN input build.
--
-- This build only concatenates already-built participant-minute tables.
--
-- Required schemas/builds:
--   5200_tl_participant_discrete_events_schema.sql
--   5200_tl_participant_discrete_events_build.sql
--   5210_tl_participant_comparison_features_schema.sql
--   5210_tl_participant_comparison_features_build.sql
--   5130_tl_participant_per_minute_stats_schema.sql

TRUNCATE TABLE game_data_filtered.tl_participant_per_minute_stats;

INSERT INTO game_data_filtered.tl_participant_per_minute_stats
(
    matchid,
    frame_timestamp,
    participantid,
    teamid,
    totalgold,
    xp,
    abilitypower,
    armor,
    armorpen,
    armorpenpercent,
    attackdamage,
    attackspeed,
    healthmax,
    magicpen,
    magicpenpercent,
    magicresist,
    movementspeed,
    currentgold,
    minionskilled,
    jungleminionskilled,
    magicdamagedonetochampions,
    magicdamagetaken,
    physicaldamagedonetochampions,
    physicaldamagetaken,
    totaldamagedonetochampions,
    totaldamagetaken,
    timeenemyspentcontrolled,
    kills,
    deaths,
    assists,
    champion_kill_bounty_gold,
    shutdown_bounty_gold,
    tower_takedowns,
    inhibitor_takedowns,
    building_kill_bounty_gold,
    elite_monster_takedowns_dragon,
    elite_monster_takedowns_rift_herald,
    elite_monster_takedowns_horde,
    elite_monster_takedowns_baron,
    wards_killed,
    wards_placed,
    turret_plates_top,
    turret_plates_mid,
    turret_plates_bot,
    legendary_item_delta,
    totalgold_team_ratio,
    totalgold_role_diff,
    totalgold_role_ratio,
    totalgold_enemy_team_diff,
    xp_team_ratio,
    xp_role_diff,
    xp_role_ratio,
    xp_enemy_team_diff,
    totalfarm_team_ratio,
    totalfarm_role_diff,
    totalfarm_role_ratio,
    totalfarm_enemy_team_diff,
    kills_team_ratio,
    kills_role_diff,
    kills_enemy_team_diff,
    deaths_role_diff,
    deaths_enemy_team_diff,
    assists_team_ratio,
    assists_role_diff,
    totaldamagedonetochampions_team_ratio,
    totaldamagedonetochampions_role_diff,
    totaldamagedonetochampions_enemy_team_diff,
    totaldamagetaken_team_ratio,
    totaldamagetaken_role_diff,
    totaldamagetaken_enemy_team_diff,
    timeenemyspentcontrolled_team_ratio,
    timeenemyspentcontrolled_role_diff,
    timeenemyspentcontrolled_enemy_team_diff,
    wards_placed_team_ratio,
    wards_placed_role_diff,
    wards_placed_enemy_team_diff,
    wards_killed_team_ratio,
    wards_killed_role_diff,
    wards_killed_enemy_team_diff,
    dragon_advantage,
    dragon_deficit,
    rift_herald_advantage,
    rift_herald_deficit,
    horde_advantage,
    horde_deficit,
    baron_advantage,
    baron_deficit
)
SELECT
    ps.matchid,
    ps.frame_timestamp,
    ps.participantid,
    pd.teamid,
    ps.totalgold,
    ps.xp,
    ps.abilitypower,
    ps.armor,
    ps.armorpen,
    ps.armorpenpercent,
    ps.attackdamage,
    ps.attackspeed,
    ps.healthmax,
    ps.magicpen,
    ps.magicpenpercent,
    ps.magicresist,
    ps.movementspeed,
    ps.currentgold,
    ps.minionskilled,
    ps.jungleminionskilled,
    ps.magicdamagedonetochampions,
    ps.magicdamagetaken,
    ps.physicaldamagedonetochampions,
    ps.physicaldamagetaken,
    ps.totaldamagedonetochampions,
    ps.totaldamagetaken,
    ps.timeenemyspentcontrolled,
    de.kills,
    de.deaths,
    de.assists,
    de.champion_kill_bounty_gold,
    de.shutdown_bounty_gold,
    de.tower_takedowns,
    de.inhibitor_takedowns,
    de.building_kill_bounty_gold,
    de.elite_monster_takedowns_dragon,
    de.elite_monster_takedowns_rift_herald,
    de.elite_monster_takedowns_horde,
    de.elite_monster_takedowns_baron,
    de.wards_killed,
    de.wards_placed,
    de.turret_plates_top,
    de.turret_plates_mid,
    de.turret_plates_bot,
    de.legendary_item_delta,
    cf.totalgold_team_ratio,
    cf.totalgold_role_diff,
    cf.totalgold_role_ratio,
    cf.totalgold_enemy_team_diff,
    cf.xp_team_ratio,
    cf.xp_role_diff,
    cf.xp_role_ratio,
    cf.xp_enemy_team_diff,
    cf.totalfarm_team_ratio,
    cf.totalfarm_role_diff,
    cf.totalfarm_role_ratio,
    cf.totalfarm_enemy_team_diff,
    cf.kills_team_ratio,
    cf.kills_role_diff,
    cf.kills_enemy_team_diff,
    cf.deaths_role_diff,
    cf.deaths_enemy_team_diff,
    cf.assists_team_ratio,
    cf.assists_role_diff,
    cf.totaldamagedonetochampions_team_ratio,
    cf.totaldamagedonetochampions_role_diff,
    cf.totaldamagedonetochampions_enemy_team_diff,
    cf.totaldamagetaken_team_ratio,
    cf.totaldamagetaken_role_diff,
    cf.totaldamagetaken_enemy_team_diff,
    cf.timeenemyspentcontrolled_team_ratio,
    cf.timeenemyspentcontrolled_role_diff,
    cf.timeenemyspentcontrolled_enemy_team_diff,
    cf.wards_placed_team_ratio,
    cf.wards_placed_role_diff,
    cf.wards_placed_enemy_team_diff,
    cf.wards_killed_team_ratio,
    cf.wards_killed_role_diff,
    cf.wards_killed_enemy_team_diff,
    cf.dragon_advantage,
    cf.dragon_deficit,
    cf.rift_herald_advantage,
    cf.rift_herald_deficit,
    cf.horde_advantage,
    cf.horde_deficit,
    cf.baron_advantage,
    cf.baron_deficit
FROM game_data_filtered.tl_participant_stats AS ps
ANY INNER JOIN game_data_filtered.participant_stats AS pd
    ON
        ps.matchid = pd.matchid
        AND ps.participantid = pd.participantid
ANY INNER JOIN game_data_filtered.tl_participant_discrete_events AS de
    ON
        ps.matchid = de.matchid
        AND ps.frame_timestamp = de.frame_timestamp
        AND ps.participantid = de.participantid
ANY INNER JOIN game_data_filtered.tl_participant_comparison_features AS cf
    ON
        ps.matchid = cf.matchid
        AND ps.frame_timestamp = cf.frame_timestamp
        AND ps.participantid = cf.participantid;
