-- noqa: disable=AL09,LT02,LT05,RF02,ST09
-- Historical champion-role-build per-minute stat averages.

TRUNCATE TABLE game_data_filtered.participant_build_minute_averages;

INSERT INTO game_data_filtered.participant_build_minute_averages
WITH
normalized AS (
    SELECT
        assumeNotNull(ps.championid) AS championid,
        ps.teamposition AS teamposition,
        ivt.highest_value_label AS build,
        ps.win AS win,
        60.0 / ps.timeplayed AS minute_scale,
        ps.firstbloodkill AS firstbloodkill,
        ps.firstbloodassist AS firstbloodassist,
        ps.firsttowerkill AS firsttowerkill,
        ps.firsttowerassist AS firsttowerassist,
        ps.champlevel AS champlevel,
        ps.champexperience * minute_scale AS champexperience,
        ps.kills * minute_scale AS kills,
        ps.deaths * minute_scale AS deaths,
        ps.assists * minute_scale AS assists,
        ps.doublekills * minute_scale AS doublekills,
        ps.triplekills * minute_scale AS triplekills,
        ps.killingsprees * minute_scale AS killingsprees,
        ps.largestkillingspree AS largestkillingspree,
        ps.largestmultikill AS largestmultikill,
        ps.goldearned * minute_scale AS goldearned,
        ps.goldspent * minute_scale AS goldspent,
        ps.totaldamagedealt * minute_scale AS totaldamagedealt,
        ps.totaldamagedealttochampions * minute_scale AS totaldamagedealttochampions,
        ps.physicaldamagedealt * minute_scale AS physicaldamagedealt,
        ps.physicaldamagedealttochampions * minute_scale AS physicaldamagedealttochampions,
        ps.magicdamagedealt * minute_scale AS magicdamagedealt,
        ps.magicdamagedealttochampions * minute_scale AS magicdamagedealttochampions,
        ps.truedamagedealt * minute_scale AS truedamagedealt,
        ps.truedamagedealttochampions * minute_scale AS truedamagedealttochampions,
        ps.damagedealttobuildings * minute_scale AS damagedealttobuildings,
        ps.damagedealttoturrets * minute_scale AS damagedealttoturrets,
        ps.damagedealttoobjectives * minute_scale AS damagedealttoobjectives,
        COALESCE(ps.damagedealttoepicmonsters, 0) * minute_scale AS damagedealttoepicmonsters,
        ps.totaldamagetaken * minute_scale AS totaldamagetaken,
        ps.physicaldamagetaken * minute_scale AS physicaldamagetaken,
        ps.magicdamagetaken * minute_scale AS magicdamagetaken,
        ps.truedamagetaken * minute_scale AS truedamagetaken,
        ps.damageselfmitigated * minute_scale AS damageselfmitigated,
        ps.totalheal * minute_scale AS totalheal,
        ps.totalhealsonteammates * minute_scale AS totalhealsonteammates,
        ps.totaldamageshieldedonteammates * minute_scale AS totaldamageshieldedonteammates,
        ps.timeccingothers * minute_scale AS timeccingothers,
        ps.totaltimeccdealt * minute_scale AS totaltimeccdealt,
        ps.totalminionskilled * minute_scale AS totalminionskilled,
        ps.neutralminionskilled * minute_scale AS neutralminionskilled,
        ps.totalallyjungleminionskilled * minute_scale AS totalallyjungleminionskilled,
        ps.totalenemyjungleminionskilled * minute_scale AS totalenemyjungleminionskilled,
        ps.baronkills * minute_scale AS baronkills,
        ps.dragonkills * minute_scale AS dragonkills,
        ps.inhibitorkills AS inhibitorkills,
        ps.inhibitortakedowns AS inhibitortakedowns,
        ps.inhibitorslost AS inhibitorslost,
        ps.turretkills AS turretkills,
        ps.turrettakedowns AS turrettakedowns,
        ps.turretslost AS turretslost,
        ps.objectivesstolen * minute_scale AS objectivesstolen,
        ps.objectivesstolenassists * minute_scale AS objectivesstolenassists,
        ps.visionscore * minute_scale AS visionscore,
        ps.wardsplaced * minute_scale AS wardsplaced,
        ps.wardskilled * minute_scale AS wardskilled,
        ps.detectorwardsplaced * minute_scale AS detectorwardsplaced,
        ps.visionwardsboughtingame * minute_scale AS visionwardsboughtingame,
        ps.totaltimespentdead * minute_scale AS totaltimespentdead,
        ps.longesttimespentliving AS longesttimespentliving,
        (
            ps.allinpings
            + ps.assistmepings
            + ps.basicpings
            + ps.commandpings
            + ps.dangerpings
            + ps.enemymissingpings
            + ps.enemyvisionpings
            + ps.getbackpings
            + ps.holdpings
            + ps.needvisionpings
            + ps.onmywaypings
            + ps.pushpings
            + COALESCE(ps.retreatpings, 0)
        ) * minute_scale AS pings
    FROM game_data_filtered.participant_stats AS ps
    ANY INNER JOIN game_data_filtered.participant_item_value_totals AS ivt
        ON
            ps.matchid = ivt.matchid
            AND ps.participantid = ivt.participantid
    WHERE
        ps.championid IS NOT NULL
        AND ps.teamposition != 'UNKNOWN'
        AND ps.timeplayed > 0
),

aggregated AS (
    SELECT
        championid,
        teamposition,
        build,
        count() AS participant_count,
        sum(win) AS n_wins,
        participant_count - n_wins AS n_losses,
        toFloat32(n_wins / participant_count) AS win_rate_raw,
        sum(firstbloodkill) AS sum_firstbloodkill,
        sum(firstbloodassist) AS sum_firstbloodassist,
        sum(firsttowerkill) AS sum_firsttowerkill,
        sum(firsttowerassist) AS sum_firsttowerassist,
        sum(champlevel) AS sum_champlevel,
        sum(champexperience) AS sum_champexperience,
        sum(kills) AS sum_kills,
        sum(deaths) AS sum_deaths,
        sum(assists) AS sum_assists,
        sum(doublekills) AS sum_doublekills,
        sum(triplekills) AS sum_triplekills,
        sum(killingsprees) AS sum_killingsprees,
        sum(largestkillingspree) AS sum_largestkillingspree,
        sum(largestmultikill) AS sum_largestmultikill,
        sum(goldearned) AS sum_goldearned,
        sum(goldspent) AS sum_goldspent,
        sum(totaldamagedealt) AS sum_totaldamagedealt,
        sum(totaldamagedealttochampions) AS sum_totaldamagedealttochampions,
        sum(physicaldamagedealt) AS sum_physicaldamagedealt,
        sum(physicaldamagedealttochampions) AS sum_physicaldamagedealttochampions,
        sum(magicdamagedealt) AS sum_magicdamagedealt,
        sum(magicdamagedealttochampions) AS sum_magicdamagedealttochampions,
        sum(truedamagedealt) AS sum_truedamagedealt,
        sum(truedamagedealttochampions) AS sum_truedamagedealttochampions,
        sum(damagedealttobuildings) AS sum_damagedealttobuildings,
        sum(damagedealttoturrets) AS sum_damagedealttoturrets,
        sum(damagedealttoobjectives) AS sum_damagedealttoobjectives,
        sum(damagedealttoepicmonsters) AS sum_damagedealttoepicmonsters,
        sum(totaldamagetaken) AS sum_totaldamagetaken,
        sum(physicaldamagetaken) AS sum_physicaldamagetaken,
        sum(magicdamagetaken) AS sum_magicdamagetaken,
        sum(truedamagetaken) AS sum_truedamagetaken,
        sum(damageselfmitigated) AS sum_damageselfmitigated,
        sum(totalheal) AS sum_totalheal,
        sum(totalhealsonteammates) AS sum_totalhealsonteammates,
        sum(totaldamageshieldedonteammates) AS sum_totaldamageshieldedonteammates,
        sum(timeccingothers) AS sum_timeccingothers,
        sum(totaltimeccdealt) AS sum_totaltimeccdealt,
        sum(totalminionskilled) AS sum_totalminionskilled,
        sum(neutralminionskilled) AS sum_neutralminionskilled,
        sum(totalallyjungleminionskilled) AS sum_totalallyjungleminionskilled,
        sum(totalenemyjungleminionskilled) AS sum_totalenemyjungleminionskilled,
        sum(baronkills) AS sum_baronkills,
        sum(dragonkills) AS sum_dragonkills,
        sum(inhibitorkills) AS sum_inhibitorkills,
        sum(inhibitortakedowns) AS sum_inhibitortakedowns,
        sum(inhibitorslost) AS sum_inhibitorslost,
        sum(turretkills) AS sum_turretkills,
        sum(turrettakedowns) AS sum_turrettakedowns,
        sum(turretslost) AS sum_turretslost,
        sum(objectivesstolen) AS sum_objectivesstolen,
        sum(objectivesstolenassists) AS sum_objectivesstolenassists,
        sum(visionscore) AS sum_visionscore,
        sum(wardsplaced) AS sum_wardsplaced,
        sum(wardskilled) AS sum_wardskilled,
        sum(detectorwardsplaced) AS sum_detectorwardsplaced,
        sum(visionwardsboughtingame) AS sum_visionwardsboughtingame,
        sum(totaltimespentdead) AS sum_totaltimespentdead,
        sum(longesttimespentliving) AS sum_longesttimespentliving,
        sum(pings) AS sum_pings
    FROM normalized
    GROUP BY championid, teamposition, build
)

SELECT
    championid,
    dictGetOrDefault('game_data.championid_name_map_dict', 'name', toString(championid), '') AS championname,
    toString(teamposition) AS teamposition,
    build,
    participant_count,
    n_wins,
    n_losses,
    win_rate_raw,
    toFloat32(sum_firstbloodkill / participant_count) AS avg_firstbloodkill,
    toFloat32(sum_firstbloodassist / participant_count) AS avg_firstbloodassist,
    toFloat32(sum_firsttowerkill / participant_count) AS avg_firsttowerkill,
    toFloat32(sum_firsttowerassist / participant_count) AS avg_firsttowerassist,
    toFloat32(sum_champlevel / participant_count) AS avg_champlevel,
    toFloat32(sum_champexperience / participant_count) AS avg_champexperience,
    toFloat32(sum_kills / participant_count) AS avg_kills,
    toFloat32(sum_deaths / participant_count) AS avg_deaths,
    toFloat32(sum_assists / participant_count) AS avg_assists,
    toFloat32(sum_doublekills / participant_count) AS avg_doublekills,
    toFloat32(sum_triplekills / participant_count) AS avg_triplekills,
    toFloat32(sum_killingsprees / participant_count) AS avg_killingsprees,
    toFloat32(sum_largestkillingspree / participant_count) AS avg_largestkillingspree,
    toFloat32(sum_largestmultikill / participant_count) AS avg_largestmultikill,
    toFloat32(sum_goldearned / participant_count) AS avg_goldearned,
    toFloat32(sum_goldspent / participant_count) AS avg_goldspent,
    toFloat32(sum_totaldamagedealt / participant_count) AS avg_totaldamagedealt,
    toFloat32(sum_totaldamagedealttochampions / participant_count) AS avg_totaldamagedealttochampions,
    toFloat32(sum_physicaldamagedealt / participant_count) AS avg_physicaldamagedealt,
    toFloat32(sum_physicaldamagedealttochampions / participant_count) AS avg_physicaldamagedealttochampions,
    toFloat32(sum_magicdamagedealt / participant_count) AS avg_magicdamagedealt,
    toFloat32(sum_magicdamagedealttochampions / participant_count) AS avg_magicdamagedealttochampions,
    toFloat32(sum_truedamagedealt / participant_count) AS avg_truedamagedealt,
    toFloat32(sum_truedamagedealttochampions / participant_count) AS avg_truedamagedealttochampions,
    toFloat32(sum_damagedealttobuildings / participant_count) AS avg_damagedealttobuildings,
    toFloat32(sum_damagedealttoturrets / participant_count) AS avg_damagedealttoturrets,
    toFloat32(sum_damagedealttoobjectives / participant_count) AS avg_damagedealttoobjectives,
    toFloat32(sum_damagedealttoepicmonsters / participant_count) AS avg_damagedealttoepicmonsters,
    toFloat32(sum_totaldamagetaken / participant_count) AS avg_totaldamagetaken,
    toFloat32(sum_physicaldamagetaken / participant_count) AS avg_physicaldamagetaken,
    toFloat32(sum_magicdamagetaken / participant_count) AS avg_magicdamagetaken,
    toFloat32(sum_truedamagetaken / participant_count) AS avg_truedamagetaken,
    toFloat32(sum_damageselfmitigated / participant_count) AS avg_damageselfmitigated,
    toFloat32(sum_totalheal / participant_count) AS avg_totalheal,
    toFloat32(sum_totalhealsonteammates / participant_count) AS avg_totalhealsonteammates,
    toFloat32(sum_totaldamageshieldedonteammates / participant_count) AS avg_totaldamageshieldedonteammates,
    toFloat32(sum_timeccingothers / participant_count) AS avg_timeccingothers,
    toFloat32(sum_totaltimeccdealt / participant_count) AS avg_totaltimeccdealt,
    toFloat32(sum_totalminionskilled / participant_count) AS avg_totalminionskilled,
    toFloat32(sum_neutralminionskilled / participant_count) AS avg_neutralminionskilled,
    toFloat32(sum_totalallyjungleminionskilled / participant_count) AS avg_totalallyjungleminionskilled,
    toFloat32(sum_totalenemyjungleminionskilled / participant_count) AS avg_totalenemyjungleminionskilled,
    toFloat32(sum_baronkills / participant_count) AS avg_baronkills,
    toFloat32(sum_dragonkills / participant_count) AS avg_dragonkills,
    toFloat32(sum_inhibitorkills / participant_count) AS avg_inhibitorkills,
    toFloat32(sum_inhibitortakedowns / participant_count) AS avg_inhibitortakedowns,
    toFloat32(sum_inhibitorslost / participant_count) AS avg_inhibitorslost,
    toFloat32(sum_turretkills / participant_count) AS avg_turretkills,
    toFloat32(sum_turrettakedowns / participant_count) AS avg_turrettakedowns,
    toFloat32(sum_turretslost / participant_count) AS avg_turretslost,
    toFloat32(sum_objectivesstolen / participant_count) AS avg_objectivesstolen,
    toFloat32(sum_objectivesstolenassists / participant_count) AS avg_objectivesstolenassists,
    toFloat32(sum_visionscore / participant_count) AS avg_visionscore,
    toFloat32(sum_wardsplaced / participant_count) AS avg_wardsplaced,
    toFloat32(sum_wardskilled / participant_count) AS avg_wardskilled,
    toFloat32(sum_detectorwardsplaced / participant_count) AS avg_detectorwardsplaced,
    toFloat32(sum_visionwardsboughtingame / participant_count) AS avg_visionwardsboughtingame,
    toFloat32(sum_totaltimespentdead / participant_count) AS avg_totaltimespentdead,
    toFloat32(sum_longesttimespentliving / participant_count) AS avg_longesttimespentliving,
    toFloat32(sum_pings / participant_count) AS avg_pings,
    toFloat32((avg_kills + avg_assists) / greatest(avg_deaths, 0.001)) AS avg_kda,
    toFloat32(avg_kills + avg_assists) AS avg_ka,
    toFloat32(avg_firstbloodkill + avg_firstbloodassist) AS avg_firstblood_participation,
    toFloat32(avg_totalhealsonteammates + avg_totaldamageshieldedonteammates) AS avg_totalprotectiononteammates,
    toFloat32((avg_totaldamagetaken + avg_damageselfmitigated) / greatest(avg_totaldamagedealttochampions, 1.0)) AS avg_expected_frontline_index,
    toFloat32(avg_totaldamagetaken + avg_damageselfmitigated + avg_totalheal) AS avg_expected_effective_durability,
    toFloat32(avg_wardskilled / greatest(avg_wardsplaced + avg_wardskilled, 0.001)) AS avg_expected_vision_denial_ratio,
    toFloat32(avg_wardsplaced + 1.5 * avg_wardskilled + 2.0 * avg_detectorwardsplaced + 2.0 * avg_visionwardsboughtingame) AS avg_expected_vision_action_score,
    toFloat32(avg_dragonkills + 2.0 * avg_baronkills + 2.0 * avg_objectivesstolen + avg_objectivesstolenassists) AS avg_expected_epic_objective_score,
    toFloat32(avg_turretkills + avg_turrettakedowns + 2.0 * avg_inhibitorkills + 2.0 * avg_inhibitortakedowns) AS avg_expected_structure_score,
    toFloat32(avg_doublekills + 2.0 * avg_triplekills + avg_killingsprees + 0.5 * avg_largestkillingspree) AS avg_expected_snowball_score,
    toFloat32(avg_totaldamagedealttochampions / greatest(avg_goldearned, 1.0)) AS avg_expected_damage_per_gold,
    toFloat32(avg_physicaldamagedealttochampions / greatest(avg_totaldamagedealttochampions, 1.0)) AS avg_expected_physical_damage_share,
    toFloat32(avg_magicdamagedealttochampions / greatest(avg_totaldamagedealttochampions, 1.0)) AS avg_expected_magic_damage_share,
    toFloat32(avg_truedamagedealttochampions / greatest(avg_totaldamagedealttochampions, 1.0)) AS avg_expected_true_damage_share,
    toFloat32(avg_totaldamagedealttochampions / greatest(avg_totaldamagetaken, 1.0)) AS avg_damage_to_taken_ratio,
    toFloat32(avg_totalminionskilled + avg_neutralminionskilled) AS avg_totalcs
FROM aggregated;
