-- noqa: disable=LT01,LT05,PRS
-- Win/loss-conditioned historical champion-role-build profiles.
-- Populated by 5134_participant_build_stat_averages_build.sql.

CREATE TABLE game_data_filtered.participant_build_minute_averages
(
    championid Int32,
    championname LowCardinality(String),
    teamposition LowCardinality(String),
    build LowCardinality(String),
    participant_count UInt64,
    n_wins UInt64,
    n_losses UInt64,
    win_rate_raw Float32,

    avg_firstbloodkill Float32,
    avg_firstbloodassist Float32,
    avg_firsttowerkill Float32,
    avg_firsttowerassist Float32,
    avg_champlevel Float32,
    avg_champexperience Float32,
    avg_kills Float32,
    avg_deaths Float32,
    avg_assists Float32,
    avg_doublekills Float32,
    avg_triplekills Float32,
    avg_killingsprees Float32,
    avg_largestkillingspree Float32,
    avg_largestmultikill Float32,
    avg_goldearned Float32,
    avg_goldspent Float32,
    avg_totaldamagedealt Float32,
    avg_totaldamagedealttochampions Float32,
    avg_physicaldamagedealt Float32,
    avg_physicaldamagedealttochampions Float32,
    avg_magicdamagedealt Float32,
    avg_magicdamagedealttochampions Float32,
    avg_truedamagedealt Float32,
    avg_truedamagedealttochampions Float32,
    avg_damagedealttobuildings Float32,
    avg_damagedealttoturrets Float32,
    avg_damagedealttoobjectives Float32,
    avg_damagedealttoepicmonsters Float32,
    avg_totaldamagetaken Float32,
    avg_physicaldamagetaken Float32,
    avg_magicdamagetaken Float32,
    avg_truedamagetaken Float32,
    avg_damageselfmitigated Float32,
    avg_totalheal Float32,
    avg_totalhealsonteammates Float32,
    avg_totaldamageshieldedonteammates Float32,
    avg_timeccingothers Float32,
    avg_totaltimeccdealt Float32,
    avg_totalminionskilled Float32,
    avg_neutralminionskilled Float32,
    avg_totalallyjungleminionskilled Float32,
    avg_totalenemyjungleminionskilled Float32,
    avg_baronkills Float32,
    avg_dragonkills Float32,
    avg_inhibitorkills Float32,
    avg_inhibitortakedowns Float32,
    avg_inhibitorslost Float32,
    avg_turretkills Float32,
    avg_turrettakedowns Float32,
    avg_turretslost Float32,
    avg_objectivesstolen Float32,
    avg_objectivesstolenassists Float32,
    avg_visionscore Float32,
    avg_wardsplaced Float32,
    avg_wardskilled Float32,
    avg_detectorwardsplaced Float32,
    avg_visionwardsboughtingame Float32,
    avg_totaltimespentdead Float32,
    avg_longesttimespentliving Float32,
    avg_pings Float32,
    avg_kda Float32,
    avg_ka Float32,
    avg_firstblood_participation Float32,
    avg_totalprotectiononteammates Float32,
    avg_expected_frontline_index Float32,
    avg_expected_effective_durability Float32,
    avg_expected_vision_denial_ratio Float32,
    avg_expected_vision_action_score Float32,
    avg_expected_epic_objective_score Float32,
    avg_expected_structure_score Float32,
    avg_expected_snowball_score Float32,
    avg_expected_damage_per_gold Float32,
    avg_expected_physical_damage_share Float32,
    avg_expected_magic_damage_share Float32,
    avg_expected_true_damage_share Float32,
    avg_damage_to_taken_ratio Float32,
    avg_totalcs Float32,
)
ENGINE = MergeTree
ORDER BY (championid, teamposition, build);
