-- noqa: disable=LT05
CREATE TABLE IF NOT EXISTS game_data_filtered.tl_participant_comparison_features
(
    matchid String,
    frame_timestamp UInt32,
    teamid UInt8,
    participantid UInt8,

    totalgold_team_ratio Float32,
    totalgold_role_diff Int64,
    totalgold_role_ratio Float32,
    totalgold_enemy_team_diff Float32,
    xp_team_ratio Float32,
    xp_role_diff Int64,
    xp_role_ratio Float32,
    xp_enemy_team_diff Float32,
    totalfarm_team_ratio Float32,
    totalfarm_role_diff Int64,
    totalfarm_role_ratio Float32,
    totalfarm_enemy_team_diff Float32,
    kills_team_ratio Float32,
    kills_role_diff Int64,
    kills_enemy_team_diff Float32,
    deaths_role_diff Int64,
    deaths_enemy_team_diff Float32,
    assists_team_ratio Float32,
    assists_role_diff Int64,
    totaldamagedonetochampions_team_ratio Float32,
    totaldamagedonetochampions_role_diff Int64,
    totaldamagedonetochampions_enemy_team_diff Float32,
    totaldamagetaken_team_ratio Float32,
    totaldamagetaken_role_diff Int64,
    totaldamagetaken_enemy_team_diff Float32,
    timeenemyspentcontrolled_team_ratio Float32,
    timeenemyspentcontrolled_role_diff Int64,
    timeenemyspentcontrolled_enemy_team_diff Float32,
    wards_placed_team_ratio Float32,
    wards_placed_role_diff Int64,
    wards_placed_enemy_team_diff Float32,
    wards_killed_team_ratio Float32,
    wards_killed_role_diff Int64,
    wards_killed_enemy_team_diff Float32,
    dragon_advantage UInt8,
    dragon_deficit UInt8,
    rift_herald_advantage UInt8,
    rift_herald_deficit UInt8,
    horde_advantage UInt8,
    horde_deficit UInt8,
    baron_advantage UInt8,
    baron_deficit UInt8
)
ENGINE = MergeTree
ORDER BY (matchid, frame_timestamp, teamid, participantid);
