-- sqlfluff: disable=PRS
-- Source is champion_basic_stats_flat.jsonl, generated by flattening champion_basic_stats.jsonl.
-- Nested stat objects (e.g. armor: {flat, perLevel}) become separate columns (armor_flat, armor_perLevel).
CREATE OR REPLACE DICTIONARY game_data.champion_basic_stats_dict
(
    _key String,
    id UInt32 DEFAULT 0,
    acquisitionRadius_flat Float32 DEFAULT 0,
    acquisitionRadius_perLevel Float32 DEFAULT 0,
    armor_flat Float32 DEFAULT 0,
    armor_perLevel Float32 DEFAULT 0,
    attackCastTime_flat Float32 DEFAULT 0,
    attackCastTime_perLevel Float32 DEFAULT 0,
    attackDamage_flat Float32 DEFAULT 0,
    attackDamage_perLevel Float32 DEFAULT 0,
    attackDelayOffset_flat Float32 DEFAULT 0,
    attackDelayOffset_perLevel Float32 DEFAULT 0,
    attackRange_flat Float32 DEFAULT 0,
    attackRange_perLevel Float32 DEFAULT 0,
    attackSpeed_flat Float32 DEFAULT 0,
    attackSpeed_perLevel Float32 DEFAULT 0,
    attackSpeedRatio_flat Float32 DEFAULT 0,
    attackSpeedRatio_perLevel Float32 DEFAULT 0,
    attackTotalTime_flat Float32 DEFAULT 0,
    attackTotalTime_perLevel Float32 DEFAULT 0,
    criticalStrikeDamage_flat Float32 DEFAULT 0,
    criticalStrikeDamage_perLevel Float32 DEFAULT 0,
    criticalStrikeDamageModifier_flat Float32 DEFAULT 0,
    criticalStrikeDamageModifier_perLevel Float32 DEFAULT 0,
    gameplayRadius_flat Float32 DEFAULT 0,
    gameplayRadius_perLevel Float32 DEFAULT 0,
    health_flat Float32 DEFAULT 0,
    health_perLevel Float32 DEFAULT 0,
    healthRegen_flat Float32 DEFAULT 0,
    healthRegen_perLevel Float32 DEFAULT 0,
    magicResistance_flat Float32 DEFAULT 0,
    magicResistance_perLevel Float32 DEFAULT 0,
    mana_flat Float32 DEFAULT 0,
    mana_perLevel Float32 DEFAULT 0,
    manaRegen_flat Float32 DEFAULT 0,
    manaRegen_perLevel Float32 DEFAULT 0,
    movespeed_flat Float32 DEFAULT 0,
    movespeed_perLevel Float32 DEFAULT 0,
    pathingRadius_flat Float32 DEFAULT 0,
    pathingRadius_perLevel Float32 DEFAULT 0,
    selectionRadius_flat Float32 DEFAULT 0,
    selectionRadius_perLevel Float32 DEFAULT 0
)
PRIMARY KEY _key
SOURCE(
    FILE(
        path '/var/lib/clickhouse/user_files/clickhouse_support/champion_basic_stats_flat.jsonl'
        format 'JSONEachRow'
    )
)
LAYOUT(HASHED())
LIFETIME(MIN 0 MAX 0);
